// infra/lib/hub-stack.ts
//
// The Success Meter Hub (api/) on AWS in Sydney. One stack, sized for a 10-20 venue pilot:
//
//   Internet -> ALB (HTTPS, ACM certificate) -> ECS Fargate "web" (FrankenPHP, /up health check)
//                                               ECS Fargate "worker" (queue) and "scheduler"
//                                               ECS Fargate "clamd" (ClamAV, internal DNS only)
//            -> RDS PostgreSQL 16 (isolated subnets, KMS-encrypted, 7-day backups)
//            -> S3 upload snapshots (KMS), KMS key for per-org data keys, SES for mail
//
// No NAT gateway: tasks run in public subnets with public IPs (for image pulls, AWS APIs and
// ClamAV signature updates) behind security groups that admit only the load balancer (web) or
// nothing at all (worker, scheduler). The database has no route to the internet. Adding NAT later
// is a subnet change, not a redesign.
//
// Secrets never enter the template: the database owner password is generated by RDS; the app
// secret's DB_APP_PASSWORD is generated here and its other keys (APP_KEY, Passport keys) are
// written once by scripts/init-secrets.sh. Only the one-off migrate task gets the owner password.

import * as cdk from 'aws-cdk-lib';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as budgets from 'aws-cdk-lib/aws-budgets';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as sm from 'aws-cdk-lib/aws-secretsmanager';
import * as ses from 'aws-cdk-lib/aws-ses';
import { Construct } from 'constructs';

export interface HubStackProps extends cdk.StackProps {
  /** Public host name of the Hub, e.g. hub.successmeter.tech. */
  domainName: string;
  /** Where budget alerts go. */
  alertEmail: string;
  /** The Revenue app's URL (invitation links), e.g. https://app.successmeter.tech. */
  frontendUrl: string;
  /** Sender for invitation mail, e.g. no-reply@successmeter.tech. Its domain is verified in SES. */
  mailFrom: string;
  /** GitHub repository allowed to deploy, "owner/name". */
  githubRepo: string;
  /** Monthly budget (USD, before credits) that triggers alerts. */
  monthlyBudgetUsd: number;
  /** Image tag for web/worker/scheduler. Unset until the first image is pushed: services stay at 0. */
  appImageTag?: string;
  /** Image tag for the migrate task (deploys migrate first, then roll the app). Defaults to appImageTag. */
  migrateImageTag?: string;
}

export class HubStack extends cdk.Stack {
  /** Sydney's zones, declared rather than looked up, so the stack synthesizes without credentials. */
  override get availabilityZones(): string[] {
    return ['ap-southeast-2a', 'ap-southeast-2b', 'ap-southeast-2c'];
  }

  constructor(scope: Construct, id: string, props: HubStackProps) {
    super(scope, id, props);

    const running = props.appImageTag !== undefined;

    // --- keys, network ---------------------------------------------------------------------

    const key = new kms.Key(this, 'DataKey', {
      alias: 'alias/success-meter-hub',
      description: 'Success Meter Hub: per-org data keys, database, snapshots, secrets',
      enableKeyRotation: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });
    // CloudWatch Logs encrypts the log groups with this key.
    key.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['kms:Encrypt*', 'kms:Decrypt*', 'kms:ReEncrypt*', 'kms:GenerateDataKey*', 'kms:Describe*'],
      principals: [new iam.ServicePrincipal(`logs.${this.region}.amazonaws.com`)],
      resources: ['*'],
      conditions: { ArnLike: { 'kms:EncryptionContext:aws:logs:arn': `arn:aws:logs:${this.region}:${this.account}:*` } },
    }));

    const vpc = new ec2.Vpc(this, 'Vpc', {
      maxAzs: 2,
      natGateways: 0,
      subnetConfiguration: [
        { name: 'public', subnetType: ec2.SubnetType.PUBLIC, cidrMask: 24 },
        { name: 'db', subnetType: ec2.SubnetType.PRIVATE_ISOLATED, cidrMask: 24 },
      ],
      flowLogs: { all: { destination: ec2.FlowLogDestination.toCloudWatchLogs(), trafficType: ec2.FlowLogTrafficType.REJECT } },
    });

    const albSg = new ec2.SecurityGroup(this, 'AlbSg', { vpc, description: 'Hub load balancer' });
    albSg.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(443), 'HTTPS');
    albSg.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(80), 'HTTP (redirects to HTTPS)');
    const appSg = new ec2.SecurityGroup(this, 'AppSg', { vpc, description: 'Hub PHP containers' });
    appSg.addIngressRule(albSg, ec2.Port.tcp(8080), 'Load balancer to web');
    const clamdSg = new ec2.SecurityGroup(this, 'ClamdSg', { vpc, description: 'ClamAV' });
    clamdSg.addIngressRule(appSg, ec2.Port.tcp(3310), 'App to clamd');
    const dbSg = new ec2.SecurityGroup(this, 'DbSg', { vpc, description: 'Hub database', allowAllOutbound: false });
    dbSg.addIngressRule(appSg, ec2.Port.tcp(5432), 'App to Postgres');

    // --- data --------------------------------------------------------------------------------

    const db = new rds.DatabaseInstance(this, 'Db', {
      engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_16 }),
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [dbSg],
      credentials: rds.Credentials.fromGeneratedSecret('hub_owner', { encryptionKey: key }),
      databaseName: 'hub',
      allocatedStorage: 20,
      maxAllocatedStorage: 100,
      storageType: rds.StorageType.GP3,
      storageEncrypted: true,
      storageEncryptionKey: key,
      backupRetention: cdk.Duration.days(7),
      deletionProtection: true,
      removalPolicy: cdk.RemovalPolicy.SNAPSHOT,
      multiAz: false,
      publiclyAccessible: false,
      cloudwatchLogsExports: ['postgresql'],
      parameters: { 'rds.force_ssl': '1' },
    });

    const snapshots = new s3.Bucket(this, 'Snapshots', {
      encryption: s3.BucketEncryption.KMS,
      encryptionKey: key,
      bucketKeyEnabled: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      // The app deletes snapshots after 90 days (ingest:prune-snapshots); this is the backstop.
      lifecycleRules: [{ expiration: cdk.Duration.days(100) }],
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const repo = new ecr.Repository(this, 'Repo', {
      repositoryName: 'success-meter-hub',
      imageScanOnPush: true,
      imageTagMutability: ecr.TagMutability.IMMUTABLE,
      lifecycleRules: [{ maxImageCount: 20 }],
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const appSecret = new sm.Secret(this, 'AppSecret', {
      secretName: 'success-meter-hub/app',
      description: 'Hub app secrets: DB_APP_PASSWORD (generated), APP_KEY and Passport keys (scripts/init-secrets.sh)',
      encryptionKey: key,
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'DB_APP_PASSWORD',
        excludePunctuation: true,
        passwordLength: 40,
      },
    });

    const mailDomain = props.mailFrom.split('@')[1];
    const mailIdentity = new ses.EmailIdentity(this, 'MailDomain', { identity: ses.Identity.domain(mailDomain) });

    // --- containers --------------------------------------------------------------------------

    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc,
      containerInsightsV2: ecs.ContainerInsights.ENABLED,
      defaultCloudMapNamespace: { name: 'hub.internal', vpc },
    });
    const logGroup = new logs.LogGroup(this, 'Logs', {
      retention: logs.RetentionDays.ONE_MONTH,
      encryptionKey: key,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const taskRole = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: 'Hub containers: KMS data keys, snapshots bucket, SES mail',
    });
    key.grant(taskRole, 'kms:GenerateDataKey', 'kms:Decrypt');
    snapshots.grantReadWrite(taskRole);
    mailIdentity.grantSendEmail(taskRole);

    const appImage = ecs.ContainerImage.fromEcrRepository(repo, props.appImageTag ?? 'not-yet-pushed');
    const migrateImage = ecs.ContainerImage.fromEcrRepository(repo, props.migrateImageTag ?? props.appImageTag ?? 'not-yet-pushed');

    const environment: Record<string, string> = {
      APP_ENV: 'production',
      APP_DEBUG: 'false',
      APP_URL: `https://${props.domainName}`,
      APP_FRONTEND_URL: props.frontendUrl,
      HUB_ISSUER: `https://${props.domainName}`,
      OPENID_FORCE_HTTPS: 'true',
      TRUSTED_PROXIES: '*',
      LOG_CHANNEL: 'stderr',
      DB_CONNECTION: 'pgsql_app',
      DB_HOST: db.dbInstanceEndpointAddress,
      DB_PORT: db.dbInstanceEndpointPort,
      DB_DATABASE: 'hub',
      DB_SSLMODE: 'require',
      DB_APP_USERNAME: 'app_user',
      SESSION_DRIVER: 'database',
      SESSION_SECURE_COOKIE: 'true',
      CACHE_STORE: 'database',
      QUEUE_CONNECTION: 'database',
      KMS_DRIVER: 'aws',
      KMS_KEY_ID: key.keyArn,
      AWS_DEFAULT_REGION: this.region,
      SNAPSHOTS_DRIVER: 's3',
      SNAPSHOTS_BUCKET: snapshots.bucketName,
      INGEST_SCANNER: 'clamav',
      CLAMD_ADDRESS: 'tcp://clamd.hub.internal:3310',
      MAIL_MAILER: 'ses',
      MAIL_FROM_ADDRESS: props.mailFrom,
      MAIL_FROM_NAME: 'Success Meter',
    };
    const appSecrets: Record<string, ecs.Secret> = {
      APP_KEY: ecs.Secret.fromSecretsManager(appSecret, 'APP_KEY'),
      DB_APP_PASSWORD: ecs.Secret.fromSecretsManager(appSecret, 'DB_APP_PASSWORD'),
      PASSPORT_PRIVATE_KEY: ecs.Secret.fromSecretsManager(appSecret, 'PASSPORT_PRIVATE_KEY'),
      PASSPORT_PUBLIC_KEY: ecs.Secret.fromSecretsManager(appSecret, 'PASSPORT_PUBLIC_KEY'),
    };

    const phpTask = (name: string, role: string, cpu: number, memoryLimitMiB: number,
      image: ecs.ContainerImage, extraSecrets: Record<string, ecs.Secret> = {}) => {
      const def = new ecs.FargateTaskDefinition(this, `${name}Task`, {
        family: `success-meter-hub-${role}`,
        cpu,
        memoryLimitMiB,
        taskRole,
        runtimePlatform: { cpuArchitecture: ecs.CpuArchitecture.X86_64, operatingSystemFamily: ecs.OperatingSystemFamily.LINUX },
      });
      def.addContainer('app', {
        image,
        command: [role],
        environment,
        secrets: { ...appSecrets, ...extraSecrets },
        logging: ecs.LogDrivers.awsLogs({ logGroup, streamPrefix: role }),
        portMappings: role === 'web' ? [{ containerPort: 8080 }] : [],
      });
      return def;
    };

    const service = (name: string, taskDefinition: ecs.FargateTaskDefinition, securityGroup: ec2.SecurityGroup,
      extra: Partial<ecs.FargateServiceProps> = {}) => new ecs.FargateService(this, name, {
      cluster,
      taskDefinition,
      desiredCount: running ? 1 : 0,
      assignPublicIp: true,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroups: [securityGroup],
      circuitBreaker: { rollback: true },
      enableExecuteCommand: true,
      ...extra,
    });

    const web = service('Web', phpTask('Web', 'web', 512, 1024, appImage), appSg, { minHealthyPercent: 100, maxHealthyPercent: 200 });
    service('Worker', phpTask('Worker', 'worker', 256, 512, appImage), appSg, { minHealthyPercent: 100, maxHealthyPercent: 200 });
    // One scheduler at a time.
    service('Scheduler', phpTask('Scheduler', 'scheduler', 256, 512, appImage), appSg, { minHealthyPercent: 0, maxHealthyPercent: 100 });

    // The migrate task is run once per deploy (scripts/deploy.sh); the only holder of the owner password.
    const migrate = phpTask('Migrate', 'migrate', 256, 512, migrateImage, {
      DB_USERNAME: ecs.Secret.fromSecretsManager(db.secret!, 'username'),
      DB_PASSWORD: ecs.Secret.fromSecretsManager(db.secret!, 'password'),
    });

    const clamdTask = new ecs.FargateTaskDefinition(this, 'ClamdTask', {
      family: 'success-meter-hub-clamd',
      cpu: 512,
      memoryLimitMiB: 3072,
      runtimePlatform: { cpuArchitecture: ecs.CpuArchitecture.X86_64, operatingSystemFamily: ecs.OperatingSystemFamily.LINUX },
    });
    clamdTask.addContainer('clamd', {
      image: ecs.ContainerImage.fromRegistry('clamav/clamav:1.4'),
      logging: ecs.LogDrivers.awsLogs({ logGroup, streamPrefix: 'clamd' }),
      portMappings: [{ containerPort: 3310 }],
    });
    new ecs.FargateService(this, 'Clamd', {
      cluster,
      taskDefinition: clamdTask,
      desiredCount: running ? 1 : 0,
      assignPublicIp: true,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroups: [clamdSg],
      circuitBreaker: { rollback: true },
      cloudMapOptions: { name: 'clamd' },
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
    });

    // --- load balancer -----------------------------------------------------------------------

    const certificate = new acm.Certificate(this, 'Certificate', {
      domainName: props.domainName,
      validation: acm.CertificateValidation.fromDns(),
    });
    const alb = new elbv2.ApplicationLoadBalancer(this, 'Alb', {
      vpc,
      internetFacing: true,
      securityGroup: albSg,
      dropInvalidHeaderFields: true,
    });
    alb.addListener('Http', { port: 80, defaultAction: elbv2.ListenerAction.redirect({ protocol: 'HTTPS', port: '443', permanent: true }) });
    const https = alb.addListener('Https', {
      port: 443,
      certificates: [certificate],
      sslPolicy: elbv2.SslPolicy.RECOMMENDED_TLS,
    });
    https.addTargets('Web', {
      port: 8080,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targets: [web],
      healthCheck: { path: '/up', healthyHttpCodes: '200', interval: cdk.Duration.seconds(30) },
      deregistrationDelay: cdk.Duration.seconds(30),
    });

    // --- spend -------------------------------------------------------------------------------

    new budgets.CfnBudget(this, 'Budget', {
      budget: {
        budgetName: 'success-meter-hub-monthly',
        budgetType: 'COST',
        timeUnit: 'MONTHLY',
        budgetLimit: { amount: props.monthlyBudgetUsd, unit: 'USD' },
        // Gross usage, before credits: otherwise credits hide the burn rate until they run out.
        costTypes: { includeCredit: false, includeRefund: false },
      },
      notificationsWithSubscribers: [
        { notification: { notificationType: 'ACTUAL', comparisonOperator: 'GREATER_THAN', threshold: 80, thresholdType: 'PERCENTAGE' },
          subscribers: [{ subscriptionType: 'EMAIL', address: props.alertEmail }] },
        { notification: { notificationType: 'FORECASTED', comparisonOperator: 'GREATER_THAN', threshold: 100, thresholdType: 'PERCENTAGE' },
          subscribers: [{ subscriptionType: 'EMAIL', address: props.alertEmail }] },
      ],
    });

    // --- deploys from GitHub Actions (main branch only) ------------------------------------

    const github = new iam.OpenIdConnectProvider(this, 'GitHubOidc', {
      url: 'https://token.actions.githubusercontent.com',
      clientIds: ['sts.amazonaws.com'],
    });
    const deployRole = new iam.Role(this, 'DeployRole', {
      roleName: 'success-meter-hub-deploy',
      description: `Deploys the Hub from ${props.githubRepo} (main branch only)`,
      maxSessionDuration: cdk.Duration.hours(1),
      assumedBy: new iam.WebIdentityPrincipal(github.openIdConnectProviderArn, {
        StringEquals: {
          'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com',
          'token.actions.githubusercontent.com:sub': `repo:${props.githubRepo}:ref:refs/heads/main`,
        },
      }),
    });
    repo.grantPullPush(deployRole);
    deployRole.addToPolicy(new iam.PolicyStatement({
      sid: 'CdkDeploy',
      actions: ['sts:AssumeRole'],
      resources: [`arn:aws:iam::${this.account}:role/cdk-hnb659fds-*-${this.account}-${this.region}`],
    }));
    deployRole.addToPolicy(new iam.PolicyStatement({
      sid: 'RunMigrations',
      actions: ['ecs:RunTask'],
      resources: [cdk.Arn.format({ service: 'ecs', resource: 'task-definition', resourceName: 'success-meter-hub-migrate:*' }, this)],
    }));
    deployRole.addToPolicy(new iam.PolicyStatement({
      sid: 'WatchMigrations',
      actions: ['ecs:DescribeTasks', 'ecs:DescribeServices', 'ecs:ListServices', 'ecs:DescribeTaskDefinition', 'ecr:DescribeImages', 'cloudformation:DescribeStacks'],
      resources: ['*'],
    }));
    deployRole.addToPolicy(new iam.PolicyStatement({
      sid: 'PassTaskRoles',
      actions: ['iam:PassRole'],
      resources: [taskRole.roleArn, migrate.executionRole!.roleArn],
    }));
    logGroup.grantRead(deployRole);

    // --- outputs -----------------------------------------------------------------------------

    const out = (id: string, value: string, description: string) => new cdk.CfnOutput(this, id, { value, description });
    out('LoadBalancerDns', alb.loadBalancerDnsName, `Point ${props.domainName} here (CNAME)`);
    out('RepositoryUri', repo.repositoryUri, 'Push Hub images here');
    out('AppSecretArn', appSecret.secretArn, 'Filled by scripts/init-secrets.sh');
    out('DeployRoleArn', deployRole.roleArn, 'GitHub variable AWS_DEPLOY_ROLE_ARN');
    out('ClusterName', cluster.clusterName, 'ECS cluster');
    out('MigrateTaskFamily', 'success-meter-hub-migrate', 'Run once per deploy');
    out('TaskSubnets', vpc.publicSubnets.map(s => s.subnetId).join(','), 'Subnets for one-off tasks');
    out('AppSecurityGroup', appSg.securityGroupId, 'Security group for one-off tasks');
    out('LogGroup', logGroup.logGroupName, 'Container logs');
    mailIdentity.dkimRecords.forEach((r, i) => out(`MailDkim${i + 1}`, `${r.name} CNAME ${r.value}`, `SES DKIM record ${i + 1} for ${mailDomain}`));

    // --- reviewed exceptions to AWS Solutions checks (cdk-nag) -----------------------------

    [
      { id: 'AwsSolutions-S1', reason: 'Snapshot bucket: object access is by the app role only; S3 access logs add a second bucket for little value at pilot scale.' },
      { id: 'AwsSolutions-ELB2', reason: 'ALB access logs add a log bucket; CloudWatch has the app logs. Revisit for launch (05 §5.6).' },
      { id: 'AwsSolutions-RDS3', reason: 'Single-AZ database for the pilot; backups every day for 7 days. Multi-AZ at launch.' },
      { id: 'AwsSolutions-RDS11', reason: 'Default Postgres port; the database is in isolated subnets and admits only the app security group.' },
      { id: 'AwsSolutions-SMG4', reason: 'Secret rotation: the app secret rotates by redeploying with a new value (db:sync-app-role); the RDS owner secret is only used by the migrate task.' },
      // Wildcards, each reviewed: CDK grants scoped to one bucket/key/log group, the execution
      // role's ECR/logs access, the CDK bootstrap role pattern, the migrate task family, and
      // read-only describe calls.
      ...[
        'Resource::*',
        `Resource::arn:aws:iam::${this.account}:role/cdk-hnb659fds-*-${this.account}-${this.region}`,
        `Resource::arn:<AWS::Partition>:ecs:${this.region}:${this.account}:task-definition/success-meter-hub-migrate:*`,
        `Resource::<${this.getLogicalId(snapshots.node.defaultChild as cdk.CfnElement)}.Arn>/*`,
        'Action::s3:List*', 'Action::s3:GetObject*', 'Action::s3:GetBucket*', 'Action::s3:DeleteObject*', 'Action::s3:Abort*',
        'Action::kms:ReEncrypt*', 'Action::kms:GenerateDataKey*',
      ].map(appliesTo => ({ id: `AwsSolutions-IAM5[${appliesTo}]`, reason: 'Reviewed wildcard: scoped CDK grant, bootstrap role pattern, migrate task family or read-only describe.' })),
      { id: 'AwsSolutions-EC23', reason: 'The load balancer is public by design (HTTPS; HTTP only redirects).' },
      { id: 'AwsSolutions-ECS2', reason: 'Non-secret configuration is passed as environment variables; secrets come from Secrets Manager.' },
      { id: 'AwsSolutions-IAM4', reason: 'AWS managed policy for the ECS task execution role (image pull, logs).' },
    ].forEach(finding => cdk.Validations.of(this).acknowledge(finding));
  }
}
