#!/usr/bin/env bash
# infra/scripts/init-web-secrets.sh
# Fills the Web Performance API's secret once, after the first `cdk deploy`: SESSION_SECRET (random)
# and GOOGLE_SERVICE_ACCOUNT_JSON (the GA4 service account key file you downloaded from Google
# Cloud). WEB_DB_PASSWORD is generated by the stack and kept. The Hub credentials are added by the
# Hub's commands (docs/hosting-aws.md, "The Web Performance tool"). Nothing is printed.
#
#   ./scripts/init-web-secrets.sh ga4-key.json     # first time
#   ./scripts/init-web-secrets.sh --ga4 ga4-key.json   # replace only the GA4 key later
set -euo pipefail

REGION=ap-southeast-2
SECRET_ID=success-meter-web/app

for tool in aws jq openssl; do
  command -v "$tool" >/dev/null || { echo "Needs $tool" >&2; exit 1; }
done

only_ga4=false
if [[ "${1:-}" == "--ga4" ]]; then only_ga4=true; shift; fi
key_file=${1:?Usage: $0 [--ga4] <ga4-service-account-key.json>}
jq -e '.type == "service_account" and (.private_key | type == "string") and (.client_email | type == "string")' "$key_file" >/dev/null \
  || { echo "$key_file is not a Google service account key (JSON)." >&2; exit 1; }

current=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$SECRET_ID" --query SecretString --output text)
if [[ "$only_ga4" == false ]] && jq -e '.SESSION_SECRET' <<<"$current" >/dev/null; then
  echo "Already initialised. Use --ga4 <file> to replace the GA4 key." >&2
  exit 1
fi

if [[ "$only_ga4" == true ]]; then
  updated=$(jq --arg ga4 "$(jq -c . "$key_file")" '. + {GOOGLE_SERVICE_ACCOUNT_JSON: $ga4}' <<<"$current")
else
  updated=$(jq --arg session "$(openssl rand -hex 48)" --arg ga4 "$(jq -c . "$key_file")" \
    '. + {SESSION_SECRET: $session, GOOGLE_SERVICE_ACCOUNT_JSON: $ga4}' <<<"$current")
fi
aws secretsmanager put-secret-value --region "$REGION" --secret-id "$SECRET_ID" --secret-string "$updated" >/dev/null
echo "Secret $SECRET_ID updated ($([[ "$only_ga4" == true ]] && echo 'GA4 key' || echo 'SESSION_SECRET, GA4 key'); WEB_DB_PASSWORD kept)."
echo "GA4: give $(jq -r .client_email "$key_file") Viewer access to each GA4 property the tool reads."
