#!/usr/bin/env bash
# infra/scripts/init-secrets.sh
# Fills the Hub's app secret once, after the first `cdk deploy`: APP_KEY and the Passport (OIDC
# signing) key pair. DB_APP_PASSWORD is already generated by the stack and is kept. Nothing is
# printed or left on disk. Run in AWS CloudShell (Sydney) or anywhere with the AWS CLI, jq, openssl.
#
#   ./scripts/init-secrets.sh            # refuses if already initialised
#   ./scripts/init-secrets.sh --rotate   # new APP_KEY and signing keys (signs everyone out)
set -euo pipefail

REGION=ap-southeast-2
SECRET_ID=success-meter-hub/app

for tool in aws jq openssl; do
  command -v "$tool" >/dev/null || { echo "Needs $tool" >&2; exit 1; }
done

current=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$SECRET_ID" --query SecretString --output text)
if [[ "${1:-}" != "--rotate" ]] && jq -e '.APP_KEY' <<<"$current" >/dev/null; then
  echo "Already initialised. Use --rotate to replace APP_KEY and the signing keys." >&2
  exit 1
fi

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
chmod 700 "$workdir"
openssl genrsa -out "$workdir/private.key" 4096 2>/dev/null
openssl rsa -in "$workdir/private.key" -pubout -out "$workdir/public.key" 2>/dev/null

updated=$(jq \
  --arg app_key "base64:$(openssl rand -base64 32)" \
  --rawfile private "$workdir/private.key" \
  --rawfile public "$workdir/public.key" \
  '. + {APP_KEY: $app_key, PASSPORT_PRIVATE_KEY: $private, PASSPORT_PUBLIC_KEY: $public}' <<<"$current")

aws secretsmanager put-secret-value --region "$REGION" --secret-id "$SECRET_ID" --secret-string "$updated" >/dev/null
echo "Secret $SECRET_ID initialised (APP_KEY, PASSPORT_PRIVATE_KEY, PASSPORT_PUBLIC_KEY; DB_APP_PASSWORD kept)."
