<?php
// api/app/Services/Encryption/AwsKmsDriver.php
namespace App\Services\Encryption;

use Aws\Kms\KmsClient;
use Illuminate\Support\Facades\DB;

/**
 * Production KMS driver (05-security.md §5.2): each org's data key is generated by AWS KMS under
 * the app's key, with the org id as encryption context, and stored only in its KMS-wrapped form
 * (org_data_keys, RLS-scoped, so callers run inside the org's tenant context). Unwrapped keys are
 * cached for the life of the process.
 */
class AwsKmsDriver implements KeyManagementService
{
    /** @var array<string, string> */
    private array $plaintext = [];

    public function __construct(private KmsClient $kms, private string $keyId) {}

    public function getOrCreateDataKey(string $orgId): string
    {
        return $this->plaintext[$orgId] ??= $this->unwrap($orgId) ?? $this->create($orgId);
    }

    public function getDataKey(string $orgId): string
    {
        return $this->plaintext[$orgId] ??= $this->unwrap($orgId)
            ?? throw new \RuntimeException("No data key exists for org {$orgId}");
    }

    public function destroyDataKey(string $orgId): void
    {
        DB::table('org_data_keys')->where('org_id', $orgId)->update(['wrapped_key' => null, 'destroyed_at' => now()]);
        unset($this->plaintext[$orgId]);
    }

    private function unwrap(string $orgId): ?string
    {
        $row = DB::table('org_data_keys')->where('org_id', $orgId)->first();
        if ($row === null) {
            return null;
        }
        if ($row->wrapped_key === null) {
            throw new \RuntimeException("The data key for org {$orgId} was destroyed");
        }

        return $this->kms->decrypt([
            'CiphertextBlob' => base64_decode($row->wrapped_key),
            'EncryptionContext' => ['org_id' => $orgId],
            'KeyId' => $this->keyId,
        ])['Plaintext'];
    }

    private function create(string $orgId): string
    {
        $result = $this->kms->generateDataKey([
            'KeyId' => $this->keyId,
            'KeySpec' => 'AES_256',
            'EncryptionContext' => ['org_id' => $orgId],
        ]);
        $inserted = DB::table('org_data_keys')->insertOrIgnore([
            'org_id' => $orgId,
            'wrapped_key' => base64_encode($result['CiphertextBlob']),
            'kms_key_id' => $this->keyId,
            'created_at' => now(),
        ]);

        // Another process created it first: use theirs, so every writer shares one key.
        return $inserted === 1 ? $result['Plaintext'] : $this->unwrap($orgId);
    }
}
